name: Deploy frontend application

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      HOST_SERVER: ${{ secrets.HOST_SERVER }}
      HOST_USER_NAME: ${{ secrets.HOST_USER_NAME }}
      HOST_SSH_PRIVATE_KEY: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: dewtks/234-deploylab-frontend:latest

      - name: Copy docker-compose file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.HOST_SERVER }}
          username: ${{ env.HOST_USER_NAME }}
          key: ${{ env.HOST_SSH_PRIVATE_KEY }}
          port: 22
          source: "docker-compose.yml"
          target: "/home/ubuntu/frontend"

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ env.HOST_SERVER }}
          username: ${{ env.HOST_USER_NAME }}
          key: ${{ env.HOST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/frontend
            echo ${{ env.DOCKER_HUB_TOKEN }} | docker login --username ${{ env.DOCKER_HUB_USERNAME }} --password-stdin
            docker compose down || echo "No running containers"
            docker compose pull
            docker compose up -d --remove-orphans
            docker system prune -f  # Cleanup old containers & images
